# Artificial Neural Network

Artificial Neural Network is used to solve the problems of Supervised Learning like Regression and Classification type of algorithms.

Neural networks reflect the behavior of the human brain, allowing computer programs to recognize patterns and solve common problems
in the fields of AI, machine learning, and deep learning.

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.9.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X)

In [ ]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [ ]:
X_train

array([[0.0, 1.0, 0.0, ..., 0, 0, 5831.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 95611.47],
       [0.0, 0.0, 1.0, ..., 1, 1, 42855.97],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

In [ ]:
X_test

array([[0.0, 1.0, 0.0, ..., 1, 1, 192852.67],
       [1.0, 0.0, 0.0, ..., 1, 0, 128702.1],
       [0.0, 0.0, 1.0, ..., 1, 1, 75732.25],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 84487.62],
       [0.0, 1.0, 0.0, ..., 1, 0, 46522.68],
       [1.0, 0.0, 0.0, ..., 0, 0, 72927.68]], dtype=object)

In [ ]:
y_train

array([1, 0, 0, ..., 0, 0, 1])

In [ ]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

### Feature Scaling

In [ ]:
# In Deep Learning it is always necessary to apply Feature Scaling to all the columns of the
# train and test set datasets.
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
X_train

array([[-1.01558815,  1.76021608, -0.57468161, ..., -1.55362351,
        -1.03446007, -1.64080994],
       [ 0.98465111, -0.56811207, -0.57468161, ...,  0.64365658,
        -1.03446007, -0.07927152],
       [-1.01558815, -0.56811207,  1.74009395, ...,  0.64365658,
         0.96668786, -0.99684012],
       ...,
       [ 0.98465111, -0.56811207, -0.57468161, ...,  0.64365658,
        -1.03446007,  1.4133552 ],
       [-1.01558815, -0.56811207,  1.74009395, ...,  0.64365658,
         0.96668786,  0.84496184],
       [-1.01558815,  1.76021608, -0.57468161, ...,  0.64365658,
        -1.03446007,  0.32500428]])

In [ ]:
X_test

array([[-0.96539827,  1.63764621, -0.57119169, ...,  0.65340695,
         0.98098083,  1.61610909],
       [ 1.03584192, -0.6106325 , -0.57119169, ...,  0.65340695,
        -1.01938791,  0.50132237],
       [-0.96539827, -0.6106325 ,  1.75072575, ...,  0.65340695,
         0.98098083, -0.41916962],
       ...,
       [ 1.03584192, -0.6106325 , -0.57119169, ...,  0.65340695,
        -1.01938791, -0.26702178],
       [-0.96539827,  1.63764621, -0.57119169, ...,  0.65340695,
        -1.01938791, -0.92676356],
       [ 1.03584192, -0.6106325 , -0.57119169, ..., -1.5304398 ,
        -1.01938791, -0.46790648]])

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=300)

Epoch 1/300
235/235 [==============================] - 2s 2ms/step - loss: 0.5166 - accuracy: 0.7943
Epoch 2/300
235/235 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.7971
Epoch 3/300
235/235 [==============================] - 0s 2ms/step - loss: 0.4383 - accuracy: 0.8045
Epoch 4/300
235/235 [==============================] - 1s 2ms/step - loss: 0.4309 - accuracy: 0.8064
Epoch 5/300
235/235 [==============================] - 0s 2ms/step - loss: 0.4257 - accuracy: 0.8091
Epoch 6/300
235/235 [==============================] - 0s 2ms/step - loss: 0.4200 - accuracy: 0.8103
Epoch 7/300
235/235 [==============================] - 0s 2ms/step - loss: 0.4130 - accuracy: 0.8163
Epoch 8/300
235/235 [==============================] - 0s 2ms/step - loss: 0.4039 - accuracy: 0.8221
Epoch 9/300
235/235 [==============================] - 0s 2ms/step - loss: 0.3921 - accuracy: 0.8328
Epoch 10/300
235/235 [==============================] - 0s 2ms/step - loss: 0.3802 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [ ]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5

1/1 [==============================] - 0s 97ms/step


array([[False]])

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)

79/79 [==============================] - 0s 2ms/step


array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(f"Confusion Matrix:\n{matrix} \nAccuracy: {accuracy}")

Confusion Matrix:
[[1892   99]
 [ 261  248]] 
Accuracy: 0.856
