# Campus Recruitment Model


## Importing the libraries


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the datasets

In [ ]:
dataset = pd.read_csv("Placement_Data_Full_Class.csv")
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -2].values

In [ ]:
print(X[0])

['M' 67.0 'Others' 91.0 'Others' 'Commerce' 58.0 'Sci&Tech' 'No' 55.0
 'Mkt&HR' 58.8]


In [ ]:
print(y)

['Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Not Placed'
 'Not Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed'
 'Not Placed' 'Placed' 'Not Placed' 'Placed' 'Placed' 'Not Placed'
 'Not Placed' 'Placed' 'Placed' 'Placed' 'Placed' 'Placed' 'Placed'
 'Not Placed' 'Placed' 'Placed' 'Placed' 'Not Placed' 'Placed'
 'Not Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Not Placed'
 'Placed' 'Placed' 'Placed' 'Placed' 'Not Placed' 'Not Placed' 'Placed'
 'Placed' 'Not Placed' 'Not Placed' 'Placed' 'Placed' 'Not Placed'
 'Placed' 'Not Placed' 'Not Placed' 'Placed' 'Placed' 'Placed' 'Placed'
 'Placed' 'Placed' 'Placed' 'Placed' 'Placed' 'Placed' 'Not Placed'
 'Placed' 'Not Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed'
 'Placed' 'Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed'
 'Placed' 'Not Placed' 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed'
 'Placed' 'Placed' 'Not Placed' 'Placed' 'Placed' 'Placed' 'Not Placed'
 'Placed' 'Not Placed' 'Placed' 'Placed' 'Plac

## Encoding the datasets

### Encoding the y values

In [ ]:
from sklearn.preprocessing import LabelEncoder

enc_y = LabelEncoder()
y = enc_y.fit_transform(y)


In [ ]:
print(y)

[1 1 1 0 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0
 1 1 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1
 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1
 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 0
 1 0 1 0 0 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 0]


### Encoding the X values

In [ ]:
from sklearn.preprocessing import LabelEncoder
# List of columns to be encoded.
# ['gender', 'ssc_b', hsc_b', 'degree_t', 'workex', 'specialization']
# cols = [0, 2, 4, 7, 8, 10]
# X[cols] = X[cols].apply(ec_X.fit_transform())

enc_X = LabelEncoder()
X[:, 0] = enc_X.fit_transform(X[:, 0].astype('str'))
X[:, 2] = enc_X.fit_transform(X[:, 2])
X[:, 4] = enc_X.fit_transform(X[:, 4])
X[:, 8] = enc_X.fit_transform(X[:, 8])
X[:, 10] = enc_X.fit_transform(X[:, 10])

In [ ]:
print(X[:5, :])

[[1 67.0 1 91.0 1 'Commerce' 58.0 'Sci&Tech' 0 55.0 1 58.8]
 [1 79.33 0 78.33 1 'Science' 77.48 'Sci&Tech' 1 86.5 0 66.28]
 [1 65.0 0 68.0 0 'Arts' 64.0 'Comm&Mgmt' 0 75.0 0 57.8]
 [1 56.0 0 52.0 0 'Science' 52.0 'Sci&Tech' 0 66.0 1 59.43]
 [1 85.8 0 73.6 0 'Commerce' 73.3 'Comm&Mgmt' 0 96.8 0 55.5]]


In [ ]:
# Applying OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [5, 7])], remainder='passthrough')
X = ct.fit_transform(X)

In [ ]:
print(X[:5])

[[0.0 1.0 0.0 0.0 0.0 1.0 1 67.0 1 91.0 1 58.0 0 55.0 1 58.8]
 [0.0 0.0 1.0 0.0 0.0 1.0 1 79.33 0 78.33 1 77.48 1 86.5 0 66.28]
 [1.0 0.0 0.0 1.0 0.0 0.0 1 65.0 0 68.0 0 64.0 0 75.0 0 57.8]
 [0.0 0.0 1.0 0.0 0.0 1.0 1 56.0 0 52.0 0 52.0 0 66.0 1 59.43]
 [0.0 1.0 0.0 1.0 0.0 0.0 1 85.8 0 73.6 0 73.3 0 96.8 0 55.5]]


## Spliting the dataset into train and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
print(X_train)

[[0.0 1.0 0.0 ... 60.0 0 62.54]
 [0.0 0.0 1.0 ... 55.6 1 65.63]
 [1.0 0.0 0.0 ... 80.4 0 71.0]
 ...
 [0.0 0.0 1.0 ... 80.0 0 67.05]
 [0.0 1.0 0.0 ... 78.0 0 54.55]
 [0.0 1.0 0.0 ... 84.0 1 52.64]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 0.0 1.0 0.0 0 67.0 0 70.0 0 65.0 0 88.0 1 71.96]
 [0.0 0.0 1.0 0.0 0.0 1.0 0 79.0 0 76.0 0 65.6 0 58.0 1 55.47]
 [0.0 0.0 1.0 0.0 0.0 1.0 0 84.0 1 75.0 1 69.0 1 62.0 1 62.36]
 [0.0 1.0 0.0 1.0 0.0 0.0 0 48.0 0 51.0 0 58.0 1 60.0 1 58.79]
 [0.0 1.0 0.0 1.0 0.0 0.0 1 80.0 1 80.0 1 72.0 1 63.79 0 66.04]
 [0.0 1.0 0.0 1.0 0.0 0.0 0 59.0 0 62.0 1 77.5 0 74.0 1 67.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 0 76.0 0 70.0 0 76.0 1 66.0 0 64.44]
 [0.0 1.0 0.0 1.0 0.0 0.0 1 67.0 1 63.0 0 72.0 0 56.0 1 60.41]
 [0.0 0.0 1.0 0.0 0.0 1.0 1 55.0 1 49.8 1 67.25 1 55.0 0 51.58]
 [0.0 0.0 1.0 0.0 0.0 1.0 1 84.0 1 79.0 1 68.0 1 84.0 0 66.69]
 [0.0 0.0 1.0 1.0 0.0 0.0 1 60.4 0 66.6 1 65.0 0 71.0 1 52.71]
 [0.0 0.0 1.0 0.0 0.0 1.0 1 89.4 1 65.66 1 71.25 0 72.0 1 63.23]
 [0.0 0.0 1.0 0.0 0.0 1.0 1 87.0 0 74.0 0 65.0 1 75.0 1 72.29]
 [0.0 1.0 0.0 1.0 0.0 0.0 1 58.0 1 61.0 1 61.0 0 58.0 1 53.94]
 [0.0 1.0 0.0 1.0 0.0 0.0 1 56.6 0 64.8 0 70.2 0 84.27 0 67.2]
 [0.0 1.0 0.0 1.0 0.0 0.0 1 55.68 1 61.33 1 56.87 0 

In [ ]:
print(y_train)

[1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1 0 0 1
 0 0 1 1 1 1 1 0 1 1 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1
 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 1
 0 0 0 0 1 0 0 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 1 1 0 1 0 0 0 0 1 1 1 1
 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 1 1 1 1]


In [ ]:
print(y_test)

[0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 1 1
 1 1 1 0 0 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.23497813  0.92166283 -0.82841687 ... -0.91848631 -0.90029235
   0.05194371]
 [-0.23497813 -1.08499548  1.20712172 ... -1.24217438  1.1107503
   0.57709192]
 [ 4.25571511 -1.08499548 -0.82841687 ...  0.58224933 -0.90029235
   1.48972813]
 ...
 [-0.23497813 -1.08499548  1.20712172 ...  0.55282314 -0.90029235
   0.81842217]
 [-0.23497813  0.92166283 -0.82841687 ...  0.40569219 -0.90029235
  -1.30596381]
 [-0.23497813  0.92166283 -0.82841687 ...  0.84708503  1.1107503
  -1.63056998]]


In [ ]:
print(X_test)

[[-0.23497813  0.92166283 -0.82841687 -1.47823719  4.25571511 -0.59525684
  -1.3662601  -0.02559788 -0.90029235  0.31034799 -1.23669388 -0.16298284
  -0.72258141  1.14134691  1.1107503   1.65288098]
 [-0.23497813 -1.08499548  1.20712172 -1.47823719 -0.23497813  1.67994709
  -1.3662601   1.12949664 -0.90029235  0.84725164 -1.23669388 -0.08327934
  -0.72258141 -1.06561725  1.1107503  -1.149609  ]
 [-0.23497813 -1.08499548  1.20712172 -1.47823719 -0.23497813  1.67994709
  -1.3662601   1.61078603  1.1107503   0.7577677   0.80860754  0.36837381
   1.38392711 -0.77135536  1.1107503   0.02135255]
 [-0.23497813  0.92166283 -0.82841687  0.67648143 -0.23497813 -0.59525684
  -1.3662601  -1.85449754 -0.90029235 -1.38984687 -1.23669388 -1.09285696
   1.38392711 -0.91848631  1.1107503  -0.58537208]
 [-0.23497813  0.92166283 -0.82841687  0.67648143 -0.23497813 -0.59525684
   0.73192505  1.22575452  1.1107503   1.2051874   0.80860754  0.76689129
   1.38392711 -0.63967317 -0.90029235  0.64677178]
 [-0.

## Training the Logistic Regression Model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

## Predicting a Single Result

In [ ]:
# classifier.predict([[0.0 1.0 0.0, 0.0 0.0 1.0, 1, 67.0, 1, 91.0, 1, 58.0, 0, 55.0, 1, 58.8]])

## Predicting the test set result

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


## Making the confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n {cm}")

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy Score: {accuracy * 100}")

Confusion Matrix:
 [[11  5]
 [ 3 24]]
Accuracy Score: 81.3953488372093
