# Introduction to Tensors using Tensorflow.

In [ ]:
# Importing the tensorflow library and checking the version of the tensorflow.
import tensorflow as tf
tf.__version__

'2.9.2'

## Scalar and its Properties

### tf.constant(value, dtype=None, shape=None, name='Const')

In [ ]:
# Creating tensors with the tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Checking the number of Dimensions of a Tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Checking the shape of a scalar.
scalar.shape

TensorShape([])

In [ ]:
# Checking the data type of the scalar
scalar.dtype

tf.int32

## Vector and its Properties

In [ ]:
# Creating a vector
vector = tf.constant([10, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

In [ ]:
# Checking the dimension of the vector
vector.ndim
# vector.shape

1

In [ ]:
# checking the datatype of the vector
vector.dtype

tf.int32

In [ ]:
# Checking the shape of the vector
vector.shape

TensorShape([2])

## Matrix and its Properties

In [ ]:
# Creating a matrix (has more than one dimensions)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Checking the dimension of the matrix
matrix.ndim

2

In [ ]:
# Creating another matrix
another_matrix = tf.constant([[10 , 3], [5, 7], [4, 6]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  3.],
       [ 5.,  7.],
       [ 4.,  6.]], dtype=float16)>

In [ ]:
# Checking the dimension of the another matrix
another_matrix.ndim

2

## Tensor and its Properties


In [ ]:
# Creating a tensor
tensor = tf.constant([[[2, 5, 4],
                       [6, 3, 1]],
                      [[5, 7, 9],
                       [8, 6, 4]],
                      [[1, 3, 4],
                       [6, 8, 3]]], name='tensor', shape=(2, 3, 3))
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[2, 5, 4],
        [6, 3, 1],
        [5, 7, 9]],

       [[8, 6, 4],
        [1, 3, 4],
        [6, 8, 3]]], dtype=int32)>

In [ ]:
# Checking the dimesnion of the tensor
tensor.ndim

3

In [ ]:
# Checking the shape of the tensor
tensor.shape

TensorShape([3, 2, 3])

In [ ]:
# Checking the data type of the tensor
tensor.dtype

tf.int32

## What we have created so far:
*   Scaler: a single number
*   Vector: a number with direction (eg. wind and direction)
*   Matrix: a 2-dimensional array of numbers
*   Tensor: an n-dimesional array of numbers (0-dimensional tensor is a scaler, 1-dimensional tensor is a vector)







## Creating tensor using 'tf.Variable'

```
tf.Variable(
    initial_value=None,
    trainable=None,
    validate_shape=True,
    caching_device=None,
    name=None,
    variable_def=None,
    dtype=None,
    import_scope=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE,
    shape=None,
    experimental_enable_variable_lifting=True
)
```


    




In [ ]:
tf.Variable
# Tensor created using tf.constant is non changeable, but the tensor created using tf.Variable is changeable.
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [ ]:
# Let's try to change the changeable tensor
print(changeable_tensor[0], '\n\n')


changeable_tensor[0] = 7
# In this way we can not change a tensor

tf.Tensor(10, shape=(), dtype=int32) 




TypeError: ignored

In [ ]:
# for changing a tensor we use the .assing() function/method.
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Now trying to change the unchangeable tensor
print(unchangeable_tensor[0])


#
unchangeable_tensor[0] = 7

tf.Tensor(10, shape=(), dtype=int32)


TypeError: ignored

In [ ]:
# Let's try the .assing() function
unchangeable_tensor[0].assign(7)

AttributeError: ignored